### ISSUE TITLE
3.1.1 Load ontology

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/profile-edit#12]
option to allow admin to load and update ontologies

**Comment by cledvina** [comment]
I'm not quite sure where this is.  I assume we are talking about "Choose Resource Template", but I could be completely off-base here.  If it is "Choose Resource Template", I can't find the storage.  I was kind of thinking we were referencing the rdf files located in /profile-edit/source/server along with vocabList.json-- but this doesn't seem to be the case.  Thanks for any pointers.

**Comment by kirkhess** [comment]
Yes, confusing! I rewrote the /profile-edit/source/server php files in nodejs, we need to deprecate the php functions in favor of node.js. 

Choose Resource Template is powered by getTemplateRefs and updateTemplateRefs,which I rewrote in recto  https://github.com/lcnetdev/recto/blob/master/server.js:107.  This updates a file templateRefs/templateRefs. Fixing this is 3.1.2.

This issue, there's a file profile-edit/source/server/vocabList.json which has specific ontology files which are stored in /profile-edit/source/server.  We need a UI (storing the list in this file is prob. ok) to specify an ontology uri and you can click one of them to update it with the current version (and maybe caching it) but everything is uri based not file based. The code is profile-edit/source/assets/js/modules/profile/services/vocab.service.js. It doesn't work very well.
