### ISSUE TITLE
3.1.3 Enhance controlled lists and valid values 

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/profile-edit#14]
Enable storing of constraints such as datatypes, pick lists, or default values

**Comment by cledvina** [comment]
Ok-- I'm not understanding this, especially the part about "The contractor shall add an option for default values to be an array of allowed literal value for a given property".

Is the "default literal" field supposed to be a dropdown with options derived from a vocabulary from the URI defined in the "Values > URI" field?

In other words: If the a Values URI is set to "http://id.loc.gov/vocabulary/issuance", then the "default literal" field should be a select box with the options of:
* integrating resource
* multipart monograph
* serial
* single unit

???

Thanks,
--Charles

**Comment by kirkhess** [comment]
We might have over summarized that one. That's one use case - so if you have a list, you can pick a default from the list.

**Comment by kirkhess** [comment]
Another is more complicated - an adhoc list of values for a literal property. 

If we enabled "note type", there is no list in ID to use, but there is a List in MARC:
http://id.loc.gov/ontologies/bibframe.html#p_noteType

This would be added as a property in the Note ResourceTemplate see
http://bibframe.org/bibliomata/profile-edit/#/profile/b488ee5c-511a-4ea6-8cfd-81eee398b13f

Then you would populate a list (I think a text box control with a list deliminted by /n is easy)

Note Type
--
Issuance information
Type of computer data
Related material
Biographical data
Administrative history
Issuing body
Index
Finding aid
Binding
Related material
Action
Exhibition
Description source
Physical details
Accompanying material
Numbering
Data source
Data not found
Musical presentation:
Computer file characteristics:
Coverage
Location
Relief
Form of original Item
Metadata entry convention
Technique
Completeness
Film inspection date

**Comment by kirkhess** [comment]
The valid values part is if you have a literal value but it is constrained by a datatype like a date or timestamp, which flows into 3.2.6

**Comment by kirkhess** [comment]
So if you look at Monograph->Instance->Projected publication date (YYMM) http://bibframe.org/bibliomata/profile-edit/#/profile/4af68062-8c00-41cb-b311-fb6c450054f6

We would add a value constraint so we get a 4 digit number (or YYMM) and then if you type something else in bfe, 3.2.6 flags it as not valid.

There's more examples of this in the Identifer profile->
http://bibframe.org/bibliomata/profile-edit/#/profile/410f8076-d0db-4acb-9d1e-719007afa9f7

Barcodes, LCCNs and LC Shelfmark all could be validated to prevent garbage being typed in.

**Comment by kirkhess** [comment]
Resolved by #26
