### ISSUE TITLE
minified css and js names vs. documentation and index.html

### ISSUE THREAD

**Issue by pmgreen** [lcnetdev/profile-edit#2]
Both the documentation and index.html refer to US-LOC-ProfileEditor.min.js and US-LOC-ProfileEditor.min.css, but the minified files that are generated in css/dist and js/dist are profile-edtior.min.css and profile-edtior.min.js, respectively.

**Comment by kirkhess** [comment]
Similar problem as #1 - package.js has a misspelling.
