### ISSUE TITLE
Exported Profile with changed order of ResourceTemplates not saved correctly

### ISSUE THREAD

**Issue by jermnelson** [lcnetdev/profile-edit#35]
Starting with a Profile that has three Resource Templates:

![screen shot 2018-11-12 at 4 19 38 pm](https://user-images.githubusercontent.com/71847/48383434-93927080-e69a-11e8-98d8-dec02564c464.png)

Swapping the order of the second and third ResourceTemplates like this:
![screen shot 2018-11-12 at 4 29 23 pm](https://user-images.githubusercontent.com/71847/48383474-bfadf180-e69a-11e8-9e14-2402b981da4e.png)

Doing a `Verbose Export` and saving the Profile locally, doesn't change the order and substitutes resourceTemplate 3 with resourceTemplate 1. Importing the profile again into the  Profile Editor, shows the error:

![screen shot 2018-11-12 at 4 44 19 pm](https://user-images.githubusercontent.com/71847/48383640-73af7c80-e69b-11e8-89fb-23ac0513e88d.png)

Attached zip file contains the original Profile (`TestLoCOrderingOriginal.json`) and the exported Profile with the attempted Resource Template swap (`TestLocOrderingSwap2to2.json`)

[profiles.zip](https://github.com/lcnetdev/profile-edit/files/2574185/profiles.zip)

This problem was originally discovered when testing the Sinopia Profile Editor (see issue [139](https://github.com/LD4P/sinopia_profile_editor/issues/139) ) and replicated at http://bibframe.org/profile-edit

**Comment by kirkhess** [comment]
Fixed #36
